spring:
 application:
   name: spring-kafka-playground-2
 cloud:
   function:
     definition: producer;consumer
   stream:
     bindings:
       consumer-in-0:
         destination: user-events
         group: some-group
       producer-out-0:
         destination: user-events


